version: '2'
services:
  snipe:
    image: snipe/snipe-it
    ports: 
      - 80:80
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=snipedb
      - DB_DATABASE=snipe
      - DB_USERNAME=snipe
      - DB_PASSWORD=snipeuserpass
      - APP_KEY=base64:5U/KPKw1GN/Rz0fWYO/4FsSOqjmjvDAQzMCqwcAqstc=
    links: 
      - snipedb:snipedb
  snipedb:
    image: mysql:8.0.3
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=snipe
      - MYSQL_USER=snipe
      - MYSQL_PASSWORD=snipeuserpass
    volumes:
      - /mysql/dumps/dir:/docker-entrypoint-initdb.d
